---
version: "3.9"
services:
  nginx-kayosports:
    depends_on:
      - kayosports
    image: nginx:1.21.6-alpine
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/.htpasswd:/etc/apache2/.htpasswd:ro
    ports:
      - 80
    networks:
      - au01
      - kayosports
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.kayosports.rule=Host(`${HOSTNAME}`) && PathPrefix(`/kayosports/`)"
      - "traefik.http.routers.kayosports.rule=Host(`${HOSTNAME}`)"
      #- "traefik.http.middlewares.stripprefix-kayosports.stripprefix.prefixes=/kayosports/"
      - "traefik.http.routers.kayosports.tls=true"
      - "traefik.http.routers.kayosports.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.kayosports.middlewares=stripprefix-kayosports"

  kayosports:
    build: ./webui/
    ports:
      - 3000
    networks:
      - kayosports
    env_file:
      - .env
    #environment:
    #  - NUXT_APP_BASE_URL=/kayosports/
   

networks:
  au01:
    external: true
  kayosports:
    name: kayosports
